export const API = {
    LOGIN: "/api/auth/login",
    REGISTER: "/api/auth/register",
    CHANGEPASSWORD: "/api/users/:id",
    DELETEACCOUNT: "/api/users/:id",
    GETAUSER: "/api/users/:id",
    FOLLOW: "/api/users/:id/follow",
    UNFOLLOW: "/api/users/:ID/unfollow",
    CREATEPOST: "/api/post",
    UPDATEPOST: "/api/post/:id",
    DELETEPOST: "/api/post/:id",
    LIKEPOST: "/api/post/:id/like",
    GETPOST: "/api/post/:id",
    TIMELINEPOST: "/api/post/timeline",
    OAUTH: "/api/auth/oauth",
};
